#!/usr/bin/env python3
"""
Send SponsorScan email notifications for newly discovered jobs.

Required environment variables
------------------------------
GMAIL_ADDRESS
    Gmail account used to send the message.

GMAIL_APP_PASSWORD
    Gmail App Password generated by the same account.

NOTIFICATION_EMAIL
    Recipient email address.

Optional environment variables
------------------------------
NEW_JOBS_CSV
    Path to the new-jobs CSV file.
    Default: new_jobs_48h.csv

SPONSORSCAN_PROFILE_NAME
    Display name included in the subject and message.
    Default: SponsorScan

REPORT_HOURS
    Report time window included in the message.
    Default: 48

EMAIL_SUBJECT_PREFIX
    Prefix used in the email subject.
    Default: SponsorScan

SMTP_HOST
    SMTP server hostname.
    Default: smtp.gmail.com

SMTP_PORT
    SMTP server port.
    Default: 465
"""

from __future__ import annotations

import csv
import mimetypes
import os
import smtplib
import ssl
import sys
from email.message import EmailMessage
from pathlib import Path
from typing import Iterable


DEFAULT_CSV = "new_jobs_48h.csv"
DEFAULT_SMTP_HOST = "smtp.gmail.com"
DEFAULT_SMTP_PORT = 465
MAX_INLINE_JOBS = 20


class EmailConfigurationError(ValueError):
    """Raised when required email configuration is missing or invalid."""


def require_env(name: str) -> str:
    value = os.getenv(name, "").strip()
    if not value:
        raise EmailConfigurationError(
            f"Required environment variable '{name}' is missing."
        )
    return value


def load_rows(path: Path) -> list[dict[str, str]]:
    if not path.exists():
        raise FileNotFoundError(f"New-jobs CSV not found: {path}")

    with path.open("r", newline="", encoding="utf-8-sig") as handle:
        reader = csv.DictReader(handle)

        if reader.fieldnames is None:
            return []

        return [
            {
                str(key): (value or "").strip()
                for key, value in row.items()
                if key is not None
            }
            for row in reader
            if any((value or "").strip() for value in row.values())
        ]


def first_present(row: dict[str, str], names: Iterable[str]) -> str:
    for name in names:
        value = row.get(name, "").strip()
        if value:
            return value
    return ""


def format_job_text(row: dict[str, str], index: int) -> str:
    company = first_present(row, ("company", "employer"))
    title = first_present(row, ("title", "job_title"))
    location = first_present(row, ("location",))
    priority = first_present(
        row,
        ("application_priority", "priority", "recommendation"),
    )
    score = first_present(row, ("combined_score", "score"))
    url = first_present(row, ("url", "apply_url", "job_url"))
    posted = first_present(row, ("posted", "posted_at", "date_posted"))

    heading_parts = [part for part in (company, title) if part]
    heading = " — ".join(heading_parts) if heading_parts else f"Job {index}"

    lines = [f"{index}. {heading}"]

    if location:
        lines.append(f"   Location: {location}")
    if priority:
        lines.append(f"   Priority: {priority}")
    if score:
        lines.append(f"   Score: {score}")
    if posted:
        lines.append(f"   Posted: {posted}")
    if url:
        lines.append(f"   Apply: {url}")

    return "\n".join(lines)


def build_plain_text(
    rows: list[dict[str, str]],
    profile_name: str,
    report_hours: str,
) -> str:
    count = len(rows)

    lines = [
        f"SponsorScan found {count} new job match{'es' if count != 1 else ''}.",
        "",
        f"Profile: {profile_name}",
        f"Report window: last {report_hours} hours",
        "",
    ]

    for index, row in enumerate(rows[:MAX_INLINE_JOBS], start=1):
        lines.append(format_job_text(row, index))
        lines.append("")

    remaining = count - MAX_INLINE_JOBS
    if remaining > 0:
        lines.append(
            f"{remaining} additional match{'es' if remaining != 1 else ''} "
            "are included in the attached CSV."
        )
        lines.append("")

    lines.extend(
        [
            "Review each original posting before applying.",
            "",
            "This message was generated automatically by SponsorScan.",
        ]
    )

    return "\n".join(lines)


def build_html(
    rows: list[dict[str, str]],
    profile_name: str,
    report_hours: str,
) -> str:
    import html

    items: list[str] = []

    for row in rows[:MAX_INLINE_JOBS]:
        company = html.escape(first_present(row, ("company", "employer")))
        title = html.escape(first_present(row, ("title", "job_title")))
        location = html.escape(first_present(row, ("location",)))
        priority = html.escape(
            first_present(
                row,
                ("application_priority", "priority", "recommendation"),
            )
        )
        score = html.escape(first_present(row, ("combined_score", "score")))
        url = first_present(row, ("url", "apply_url", "job_url"))

        heading = " — ".join(part for part in (company, title) if part)
        if not heading:
            heading = "Job match"

        metadata = []
        if location:
            metadata.append(f"Location: {location}")
        if priority:
            metadata.append(f"Priority: {priority}")
        if score:
            metadata.append(f"Score: {score}")

        meta_html = "<br>".join(metadata)

        if url:
            safe_url = html.escape(url, quote=True)
            link_html = f'<br><a href="{safe_url}">View posting</a>'
        else:
            link_html = ""

        items.append(
            "<li style=\"margin-bottom:16px;\">"
            f"<strong>{heading}</strong>"
            + (f"<br>{meta_html}" if meta_html else "")
            + link_html
            + "</li>"
        )

    remaining = len(rows) - MAX_INLINE_JOBS
    extra = (
        f"<p>{remaining} additional match"
        f"{'es' if remaining != 1 else ''} are included in the attached CSV.</p>"
        if remaining > 0
        else ""
    )

    return f"""\
<html>
  <body>
    <p>
      SponsorScan found <strong>{len(rows)}</strong> new job
      match{'es' if len(rows) != 1 else ''}.
    </p>
    <p>
      Profile: {html.escape(profile_name)}<br>
      Report window: last {html.escape(report_hours)} hours
    </p>
    <ol>
      {''.join(items)}
    </ol>
    {extra}
    <p>Review each original posting before applying.</p>
    <p><small>This message was generated automatically by SponsorScan.</small></p>
  </body>
</html>
"""


def attach_csv(message: EmailMessage, path: Path) -> None:
    mime_type, _ = mimetypes.guess_type(path.name)
    if mime_type:
        maintype, subtype = mime_type.split("/", 1)
    else:
        maintype, subtype = "text", "csv"

    message.add_attachment(
        path.read_bytes(),
        maintype=maintype,
        subtype=subtype,
        filename=path.name,
    )


def send_email(
    sender: str,
    app_password: str,
    recipient: str,
    subject: str,
    plain_text: str,
    html_text: str,
    attachment: Path,
    smtp_host: str,
    smtp_port: int,
) -> None:
    message = EmailMessage()
    message["From"] = sender
    message["To"] = recipient
    message["Subject"] = subject

    message.set_content(plain_text)
    message.add_alternative(html_text, subtype="html")
    attach_csv(message, attachment)

    context = ssl.create_default_context()

    with smtplib.SMTP_SSL(
        smtp_host,
        smtp_port,
        context=context,
        timeout=30,
    ) as smtp:
        smtp.login(sender, app_password)
        smtp.send_message(message)


def main() -> int:
    try:
        sender = require_env("GMAIL_ADDRESS")
        app_password = require_env("GMAIL_APP_PASSWORD")
        recipient = require_env("NOTIFICATION_EMAIL")

        csv_path = Path(os.getenv("NEW_JOBS_CSV", DEFAULT_CSV)).expanduser()
        profile_name = os.getenv(
            "SPONSORSCAN_PROFILE_NAME",
            "SponsorScan",
        ).strip() or "SponsorScan"
        report_hours = os.getenv("REPORT_HOURS", "48").strip() or "48"
        subject_prefix = os.getenv(
            "EMAIL_SUBJECT_PREFIX",
            "SponsorScan",
        ).strip() or "SponsorScan"
        smtp_host = os.getenv("SMTP_HOST", DEFAULT_SMTP_HOST).strip()
        smtp_port = int(os.getenv("SMTP_PORT", str(DEFAULT_SMTP_PORT)))

        rows = load_rows(csv_path)

        if not rows:
            print(
                f"No new jobs were found in {csv_path}. "
                "Skipping email notification."
            )
            return 0

        count = len(rows)
        subject = (
            f"{subject_prefix}: {count} new job "
            f"match{'es' if count != 1 else ''}"
        )

        plain_text = build_plain_text(rows, profile_name, report_hours)
        html_text = build_html(rows, profile_name, report_hours)

        send_email(
            sender=sender,
            app_password=app_password,
            recipient=recipient,
            subject=subject,
            plain_text=plain_text,
            html_text=html_text,
            attachment=csv_path,
            smtp_host=smtp_host,
            smtp_port=smtp_port,
        )

        print(
            f"Sent {count} new job match"
            f"{'es' if count != 1 else ''} to {recipient}."
        )
        return 0

    except (
        EmailConfigurationError,
        FileNotFoundError,
        ValueError,
        OSError,
        smtplib.SMTPException,
    ) as exc:
        print(f"Email notification failed: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
